<?php
    session_start();

    include("Header.php");
$db = new PDO("mysql:dbname=samras4_db;host=localhost", "samras4", "wick64nidi");

$db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

        
        if(isset($_POST['username'])){
            $username = $db->quote($_POST['username']);

            $email = $db->quote($_POST['email']);

            $password = $db->quote(md5($_POST['password']));

            $password2 = $db->quote(md5($_POST['password2']));


            if($password == $password2){

               
                $sql ="INSERT INTO users(username, email, password) VALUES($username, $email, $password)";

                $dbQuery = $db->prepare($sql);

                $dbQuery->execute();
	
                $_SESSION['message'] = "You are now logged in";

                $_SESSION['username'] = $username;

                header("location: home.php");

            }
            
else{
                $_SESSION['message'] = "The two password do not match";

                
            }

    
        }
 
?>

<!DOCTYPE html>

<html>

    <head>

        <title> FiLo system </title>

        <link rel="stylesheet" type="text/css" href="style.css">

    </head>

    <body>


    <?php
        if (isset($_SESSION['message'])){

            echo "<div id='error_msg'>".$_SESSION['message']."</div>";

            unset($_SESSION['message']);

        }

    ?>

        <h2> Register</h2>

        <form method ="post" action ="register.php">

            <table>

                <tr>

                    <td>Username:</td>


                    <td><input type="text" name="username" class="textInput"required/></td>

                </tr>
                <tr>

                    <td>Email:</td>

                    <td><input type="email" name="email" class="textInput" required/></td>

                </tr>
                <tr>

                    <td>Password:</td>

                    <td><input type="password" name="password" class="textInput" required/></td>
 
                </tr>
                <tr>

                    <td>Password:</td>

                    <td><input type="password" name="password2" class="textInput"required/></td>
 
                </tr>
                <tr>

                    <td></td>

                    <td><input type ="submit" name="register_btn" value ="Register"/></td>

                </tr>

            </table>

        </form>


    </body>

</html>

